from app.ml.dataset import (
    build_training_dataset,
    chronological_surveys_by_employee,
    format_coverage_report,
    summarize_training_coverage,
)
from app.ml.features import COMPACT_FEATURE_NAMES, build_feature_row, compact_feature_vector, survey_block_percentages, survey_essi
from app.ml.predict import build_latest_feature_rows, run_inference
from app.ml.recommendations import aggregate_department_risks, build_recommendation_drafts
from app.ml.storage import (
    artifact_dir,
    find_artifact_by_model_version,
    latest_artifact_path,
    list_artifacts,
    load_model,
    manifest_path,
    read_active_manifest,
    read_artifact_status,
    resolve_runtime_artifact,
    save_model,
    write_active_manifest,
)
from app.ml.train import format_training_report, train_baseline_model
from app.ml.types import (
    ActiveManifest,
    ArtifactInfo,
    ArtifactStatus,
    CoverageSummary,
    DatasetRow,
    DepartmentRiskSummary,
    FeatureRow,
    InferenceEmployeeResult,
    InferenceRunResult,
    MLRunRecord,
    PromoteResult,
    RecommendationDraft,
    TrainingMetrics,
    TrainingResult,
)

__all__ = [
    "ActiveManifest",
    "ArtifactInfo",
    "ArtifactStatus",
    "CoverageSummary",
    "DatasetRow",
    "DepartmentRiskSummary",
    "FeatureRow",
    "InferenceEmployeeResult",
    "InferenceRunResult",
    "PromoteResult",
    "RecommendationDraft",
    "TrainingMetrics",
    "TrainingResult",
    "COMPACT_FEATURE_NAMES",
    "aggregate_department_risks",
    "artifact_dir",
    "build_feature_row",
    "build_latest_feature_rows",
    "build_recommendation_drafts",
    "build_training_dataset",
    "chronological_surveys_by_employee",
    "compact_feature_vector",
    "find_artifact_by_model_version",
    "format_coverage_report",
    "format_training_report",
    "latest_artifact_path",
    "list_artifacts",
    "load_model",
    "manifest_path",
    "read_active_manifest",
    "read_artifact_status",
    "resolve_runtime_artifact",
    "run_inference",
    "save_model",
    "summarize_training_coverage",
    "survey_block_percentages",
    "survey_essi",
    "train_baseline_model",
    "write_active_manifest",
]
